version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - store_artifacts:
          path: target/site/apidocs
          destination: javadoc

  deploy-github-pages:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.name 'CircleCI'
            git config --global user.email 'circleci@example.com'
            git checkout gh-pages || git checkout -b gh-pages
            git rm -rf .
            cp -r target/site/apidocs/* .
            git add .
            git commit -m "Update GitHub Pages [skip ci]"
            git push origin gh-pages
      
workflows:
  sample:
    jobs:
      - build-and-test
      - deploy-github-pages:
          requires:
            - build-and-test
          filters:
            branches:
              only: main