version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk

    steps:
      - checkout

      - run:
          name: Install Maven
          command: apt-get update && apt-get install -y maven

      - run:
          name: Run Unit Tests
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master