version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check

  documentation:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Move Javadoc to root/docs/
          command: |
            mkdir -p docs
            mv target/site/apidocs/* docs/
      - run:
          name: Commit and Push Javadoc
          command: |
            git config --global user.email ""
            git config --global user.name "Documentation Bot"
            git add docs
            git commit -m "Update Javadoc"
            git push origin $(git rev-parse --abbrev-ref HEAD)

workflows:
  sample:
    jobs:
      - build-and-test
      - documentation:
          requires:
            - build-and-test