version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

permissions:
  contents: write

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check

  documentation:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Publish Documentation to documentation Branch
          command: |
            git config user.name "DocumentationBot"
            git config user.email "doc@example.com"

            # Check if the documentation branch exists
            if git show-ref --quiet refs/heads/documentation; then
              git checkout documentation
            else
              git checkout -b documentation
            fi

            # Remove old docs content if exists
            rm -rf docs/*

            # Copy the new Javadoc files to docs directory
            mkdir -p docs
            cp -r target/site/apidocs/* docs/

            # Commit and push changes
            git add docs
            git commit -m "Update Javadoc documentation [skip ci]"
            git push origin documentation --force

workflows:
  sample:
    jobs:
      - build-and-test
      - documentation:
          requires:
            - build-and-test